import { Category } from "./types";

export const categories: (Category & { icon: string; photos: string[] })[] = [
  {
    slug: "muscle-recovery",
    name: "Muscle & Recovery",
    description: "Researched for muscle growth, recovery, and tissue repair",
    icon: "/category-recovery.png",
    photos: [
      "/category-photo-recovery.jpg",
      "/category-photo-recovery-1.jpg",
      "/category-photo-recovery-2.jpg",
      "/category-photo-recovery-3.jpg",
    ],
  },
  {
    slug: "fat-loss",
    name: "Fat Loss & Metabolism",
    description: "Researched for body composition and metabolic pathways",
    icon: "/category-fatloss.png",
    photos: [
      "/category-photo-fatloss.jpg",
      "/category-photo-fatloss-1.jpg",
      "/category-photo-fatloss-2.jpg",
      "/category-photo-fatloss-3.jpg",
    ],
  },
  {
    slug: "anti-aging",
    name: "Anti-Aging & Longevity",
    description: "Researched for healthy aging and longevity",
    icon: "/category-antiaging.png",
    photos: [
      "/category-photo-antiaging.jpg",
      "/category-photo-antiaging-1.jpg",
      "/category-photo-antiaging-2.jpg",
      "/category-photo-antiaging-3.jpg",
    ],
  },
  {
    slug: "sexual-health",
    name: "Sexual Health",
    description: "Researched for libido and sexual function",
    icon: "/category-sexualhealth.png",
    photos: [
      "/category-photo-sexualhealth.jpg",
      "/category-photo-sexualhealth-1.jpg",
      "/category-photo-sexualhealth-2.jpg",
      "/category-photo-sexualhealth-3.jpg",
    ],
  },
  {
    slug: "skin-hair",
    name: "Skin & Hair",
    description: "Researched for collagen, skin, and hair",
    icon: "/category-skincare.png",
    photos: [
      "/category-photo-skincare.jpg",
      "/category-photo-skincare-1.jpg",
      "/category-photo-skincare-2.jpg",
      "/category-photo-skincare-3.jpg",
    ],
  },
  {
    slug: "cognitive-research",
    name: "Cognitive Research",
    description: "Researched for memory, focus, and neurological function",
    icon: "/category-cognitive.png",
    photos: [
      "/category-photo-cognitive.jpg",
      "/category-photo-cognitive-1.jpg",
      "/category-photo-cognitive-2.jpg",
      "/category-photo-cognitive-3.jpg",
    ],
  },
  {
    slug: "immune-research",
    name: "Immune Research",
    description: "Researched for immune system modulation",
    icon: "/category-immune.png",
    photos: [
      "/category-photo-immune.jpg",
      "/category-photo-immune-1.jpg",
      "/category-photo-immune-2.jpg",
      "/category-photo-immune-3.jpg",
    ],
  },
  {
    slug: "hormone-research",
    name: "Hormone Research",
    description: "Researched for endocrine and hormone signaling",
    icon: "/category-hormone.png",
    photos: [
      "/category-photo-hormone.jpg",
      "/category-photo-hormone-1.jpg",
      "/category-photo-hormone-2.jpg",
      "/category-photo-hormone-3.jpg",
    ],
  },
  {
    slug: "pigmentation-research",
    name: "Pigmentation Research",
    description: "Researched for melanin production",
    icon: "/category-pigmentation.png",
    photos: [
      "/category-photo-pigmentation.jpg",
      "/category-photo-pigmentation-1.jpg",
      "/category-photo-pigmentation-2.jpg",
      "/category-photo-pigmentation-3.jpg",
    ],
  },
  {
    slug: "research-tools",
    name: "Research Tools",
    description: "Laboratory supplies used alongside peptide research",
    icon: "/category-researchtools.png",
    photos: [
      "/category-photo-researchtools.jpg",
      "/category-photo-researchtools-1.jpg",
      "/category-photo-researchtools-2.jpg",
      "/category-photo-researchtools-3.jpg",
    ],
  },
  {
    slug: "oncology-research",
    name: "Oncology Research",
    description: "Peptides researched for tumor-selective cell targeting",
    icon: "/category-oncology.png",
    photos: [
      "/category-photo-oncology.jpg",
      "/category-photo-oncology-1.jpg",
      "/category-photo-oncology-2.jpg",
      "/category-photo-oncology-3.jpg",
    ],
  },
  {
    slug: "research-compounds",
    name: "Research Compounds",
    description: "Non-peptide small molecules sold alongside peptide research",
    icon: "/category-compounds.png",
    photos: [
      "/category-photo-compounds.jpg",
      "/category-photo-compounds-1.jpg",
      "/category-photo-compounds-2.jpg",
      "/category-photo-compounds-3.jpg",
    ],
  },
  {
    slug: "bone-joint-research",
    name: "Bone & Joint Research",
    description: "Researched for bone density and skeletal signaling",
    icon: "/category-bonejoint.png",
    photos: [
      "/category-photo-bonejoint.jpg",
      "/category-photo-bonejoint-1.jpg",
      "/category-photo-bonejoint-2.jpg",
      "/category-photo-bonejoint-3.jpg",
    ],
  },
  {
    slug: "cardiovascular-research",
    name: "Cardiovascular Research",
    description: "Researched for vascular and cardiac signaling pathways",
    icon: "/category-cardio.png",
    photos: [
      "/category-photo-cardio.jpg",
      "/category-photo-cardio-1.jpg",
      "/category-photo-cardio-2.jpg",
      "/category-photo-cardio-3.jpg",
    ],
  },
  {
    slug: "pain-neuropeptide-research",
    name: "Pain & Neuropeptide Research",
    description: "Researched for opioid receptor and pain-signaling pathways",
    icon: "/category-pain.png",
    photos: [
      "/category-photo-pain.jpg",
      "/category-photo-pain-1.jpg",
      "/category-photo-pain-2.jpg",
      "/category-photo-pain-3.jpg",
    ],
  },
];